import { z } from "zod";

export const TransactionsFormatSchema = z.enum(["json", "xml", "csv"]);

export const TransactionsQueryParamsSchema = z
  .object({
    from: z.string().nullish(),
    to: z.string().nullish(),
    limit: z.number().int().positive().max(4000).nullish(),
    transaction_id: z.string().nullish(),
    call_record_id: z.string().nullish(),
    start_after_transaction_id: z.string().nullish(),
    include_columns: z.array(z.string()).nullish(),
    exclude_columns: z.array(z.string()).nullish(),
    transaction_type: z.string().nullish(),
    format: TransactionsFormatSchema.nullish(),
  })
  .passthrough();

export type TransactionsQueryParams = z.infer<typeof TransactionsQueryParamsSchema>;

export const TransactionCustomDataItemSchema = z
  .object({
    name: z.string().nullish(),
    data_type: z.string().nullish(),
    source: z.string().nullish(),
    value: z.union([z.string(), z.boolean(), z.null()]).nullish(),
  })
  .passthrough();

export type TransactionCustomDataItem = z.infer<typeof TransactionCustomDataItemSchema>;

export const TransactionSchema = z
  .object({
    transaction_id: z.string().nullish(),
    complete_call_id: z.string().nullish(),
    call_record_id: z.string().nullish(),
    transaction_type: z.string().nullish(),
    start_time_local: z.string().nullish(),
    start_time_utc: z.union([z.string(), z.number()]).nullish(),
    start_time_xml: z.string().nullish(),
    start_time_network_timezone: z.string().nullish(),
    start_time_network_timezone_xml: z.string().nullish(),
    duration: z.union([z.string(), z.number()]).nullish(),
    connect_duration: z.union([z.string(), z.number()]).nullish(),
    ivr_duration: z.union([z.string(), z.number()]).nullish(),
    calling_phone_number: z.string().nullish(),
    destination_phone_number: z.string().nullish(),
    city: z.string().nullish(),
    region: z.string().nullish(),
    mobile: z.string().nullish(),
    repeat_calling_phone_number: z.union([z.string(), z.boolean()]).nullish(),
    recording: z.string().nullish(),
    notes: z.string().nullish(),
    media_type: z.string().nullish(),
    call_source_description: z.string().nullish(),
    call_result_description_detail: z.string().nullish(),
    call_result_description_detail_managed_advertiser: z.string().nullish(),
    transfer_from_type: z.string().nullish(),
    verified_zip: z.string().nullish(),
    qualified_regions: z.string().nullish(),
    opt_in_SMS: z.union([z.string(), z.boolean()]).nullish(),
    virtual_line_id: z.string().nullish(),
    syndicated_ident: z.string().nullish(),
    hangup_cause: z.string().nullish(),
    advertiser_campaign_id: z.string().nullish(),
    advertiser_campaign_id_from_network: z.string().nullish(),
    advertiser_campaign_name: z.string().nullish(),
    advertiser_campaign_country: z.string().nullish(),
    advertiser_payin_localized: z.string().nullish(),
    advertiser_promo_line_description: z.string().nullish(),
    advertiser_id: z.string().nullish(),
    advertiser_id_from_network: z.string().nullish(),
    advertiser_name: z.string().nullish(),
    advertiser_call_fee_localized: z.string().nullish(),
    affiliate_id: z.string().nullish(),
    affiliate_id_from_network: z.string().nullish(),
    affiliate_name: z.string().nullish(),
    affiliate_payout_localized: z.string().nullish(),
    affiliate_call_volume_ranking: z.union([z.string(), z.number()]).nullish(),
    affiliate_commissions_ranking: z.union([z.string(), z.number()]).nullish(),
    affiliate_conversion_rate_ranking: z.union([z.string(), z.number()]).nullish(),
    affiliate_campaign_id_from_network: z.string().nullish(),
    matching_advertiser_payin_policies: z.string().nullish(),
    matching_affiliate_payout_policies: z.string().nullish(),
    payin_conditions: z.string().nullish(),
    payout_conditions: z.string().nullish(),
    margin_localized: z.string().nullish(),
    call_fee_localized: z.string().nullish(),
    promo_line_description: z.string().nullish(),
    real_time_response: z.string().nullish(),
    corrected_at: z.string().nullish(),
    corrects_transaction_id: z.string().nullish(),
    original_order_id: z.string().nullish(),
    keypress_1: z.string().nullish(),
    keypress_2: z.string().nullish(),
    keypress_3: z.string().nullish(),
    keypress_4: z.string().nullish(),
    keypresses: z.string().nullish(),
    dynamic_number_pool_id: z.string().nullish(),
    dynamic_number_pool_pool_type: z.string().nullish(),
    dynamic_number_pool_referrer_search_engine: z.string().nullish(),
    dynamic_number_pool_referrer_search_keywords: z.string().nullish(),
    dynamic_number_pool_referrer_search_type: z.string().nullish(),
    dynamic_number_pool_referrer_ad: z.string().nullish(),
    dynamic_number_pool_referrer_ad_group: z.string().nullish(),
    dynamic_number_pool_referrer_ad_group_id: z.string().nullish(),
    dynamic_number_pool_referrer_ad_id: z.string().nullish(),
    dynamic_number_pool_referrer_referrer_campaign: z.string().nullish(),
    dynamic_number_pool_referrer_referrer_campaign_id: z.string().nullish(),
    dynamic_number_pool_referrer_search_keywords_id: z.string().nullish(),
    dynamic_number_pool_referrer_keyword_match_type: z.string().nullish(),
    dynamic_number_pool_referrer_param1_name: z.string().nullish(),
    dynamic_number_pool_referrer_param1_value: z.string().nullish(),
    dynamic_number_pool_referrer_param2_name: z.string().nullish(),
    dynamic_number_pool_referrer_param2_value: z.string().nullish(),
    dynamic_number_pool_referrer_param3_name: z.string().nullish(),
    dynamic_number_pool_referrer_param3_value: z.string().nullish(),
    dynamic_number_pool_referrer_param4_name: z.string().nullish(),
    dynamic_number_pool_referrer_param4_value: z.string().nullish(),
    dynamic_number_pool_referrer_param5_name: z.string().nullish(),
    dynamic_number_pool_referrer_param5_value: z.string().nullish(),
    dynamic_number_pool_referrer_param6_name: z.string().nullish(),
    dynamic_number_pool_referrer_param6_value: z.string().nullish(),
    dynamic_number_pool_referrer_param7_name: z.string().nullish(),
    dynamic_number_pool_referrer_param7_value: z.string().nullish(),
    dynamic_number_pool_referrer_param8_name: z.string().nullish(),
    dynamic_number_pool_referrer_param8_value: z.string().nullish(),
    dynamic_number_pool_referrer_param9_name: z.string().nullish(),
    dynamic_number_pool_referrer_param9_value: z.string().nullish(),
    dynamic_number_pool_referrer_param10_name: z.string().nullish(),
    dynamic_number_pool_referrer_param10_value: z.string().nullish(),
    recording_download_url: z.string().nullish(),
    during_hours: z.string().nullish(),
    start_time_destination: z.string().nullish(),
    address1: z.string().nullish(),
    address2: z.string().nullish(),
    cell_phone_number: z.string().nullish(),
    country: z.string().nullish(),
    email_address: z.string().nullish(),
    home_phone_number: z.string().nullish(),
    name: z.string().nullish(),
    order_city: z.string().nullish(),
    quantity_list: z.string().nullish(),
    reason_code: z.string().nullish(),
    sale_amount: z.union([z.string(), z.number()]).nullish(),
    sku_list: z.string().nullish(),
    state_or_province: z.string().nullish(),
    zip_code: z.string().nullish(),
    signal_name: z.string().nullish(),
    signal_description: z.string().nullish(),
    signal_partner_unique_id: z.string().nullish(),
    signal_occurred_at: z.union([z.string(), z.number()]).nullish(),
    signal_source: z.string().nullish(),
    signal_value: z.union([z.string(), z.boolean(), z.null()]).nullish(),
    signal_custom_parameter_1: z.string().nullish(),
    signal_custom_parameter_2: z.string().nullish(),
    signal_custom_parameter_3: z.string().nullish(),
    revenue: z.union([z.string(), z.number()]).nullish(),
    custom_data: z.array(TransactionCustomDataItemSchema).nullish(),
    external_data: z.string().nullish(),
  })
  .passthrough();

export type Transaction = z.infer<typeof TransactionSchema>;

export const TransactionsPageSchema = z.union([
  z.array(TransactionSchema),
  z
    .object({
      transactions: z.array(TransactionSchema),
      next_cursor: z.string().nullish(),
    })
    .passthrough(),
]);

export type TransactionsPage = z.infer<typeof TransactionsPageSchema>;
